// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.11.2
// source: api/bff/interface/v1/user.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserInterfaceClient is the client API for UserInterface configs.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserInterfaceClient interface {
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoReply, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error)
}

type userInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserInterfaceClient(cc grpc.ClientConnInterface) UserInterfaceClient {
	return &userInterfaceClient{cc}
}

func (c *userInterfaceClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoReply, error) {
	out := new(GetUserInfoReply)
	err := c.cc.Invoke(ctx, "/api.bff.interface.v1.UserInterface/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInterfaceClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/api.bff.interface.v1.UserInterface/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInterfaceServer is the server API for UserInterface configs.
// All implementations must embed UnimplementedUserInterfaceServer
// for forward compatibility
type UserInterfaceServer interface {
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoReply, error)
	Login(context.Context, *LoginReq) (*LoginReply, error)
	mustEmbedUnimplementedUserInterfaceServer()
}

// UnimplementedUserInterfaceServer must be embedded to have forward compatible implementations.
type UnimplementedUserInterfaceServer struct {
}

func (UnimplementedUserInterfaceServer) GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserInterfaceServer) Login(context.Context, *LoginReq) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserInterfaceServer) mustEmbedUnimplementedUserInterfaceServer() {}

// UnsafeUserInterfaceServer may be embedded to opt out of forward compatibility for this configs.
// Use of this interface is not recommended, as added methods to UserInterfaceServer will
// result in compilation errors.
type UnsafeUserInterfaceServer interface {
	mustEmbedUnimplementedUserInterfaceServer()
}

func RegisterUserInterfaceServer(s grpc.ServiceRegistrar, srv UserInterfaceServer) {
	s.RegisterService(&UserInterface_ServiceDesc, srv)
}

func _UserInterface_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInterfaceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.bff.interface.v1.UserInterface/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInterfaceServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInterface_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInterfaceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.bff.interface.v1.UserInterface/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInterfaceServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserInterface_ServiceDesc is the grpc.ServiceDesc for UserInterface configs.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bff.interface.v1.UserInterface",
	HandlerType: (*UserInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UserInterface_GetUserInfo_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserInterface_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/bff/interface/v1/user.proto",
}
