server:
  name: "kratos.bff.api"
  version: "1.0"
  http:
    addr: 0.0.0.0:8000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 10s

data:
  database:
    driver: mysql
    source: root:123456@tcp(user-db:3306)/user?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: cache-redis:6379
    password: "123456"
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  key: some-secret-key

discovery:
  consul:
    addr: consul:8500
    scheme: http
registry:
  consul:
    addr: consul:8500
    scheme: http

trace:
  enable: true
  endpoint: http://jaeger:14268/api/traces
  trace_file_path: ./log/trace.log
  exporter: jaeger
  token: