version: '3'
networks:
  app_kratos-net:
    external: true
services:
  kratos-bff-interface:
    image: go-kratos/kratos-bff:0.1.0
    hostname: kratos-bff
    ports:
      - 8000:8000
    volumes:
      - ./configs/bff.yaml:/data/conf.yaml
    restart: always
    networks:
      - app_kratos-net
  kratos-user-service:
    image: go-kratos/kratos-user:0.1.0
    hostname: kratos-user
    volumes:
      - ./configs/user.yaml:/data/conf.yaml
    restart: always
    networks:
      - app_kratos-net
  kratos-order-service:
    image: go-kratos/kratos-order:0.1.0
    hostname: kratos-order
    volumes:
      - ./configs/order.yaml:/data/conf.yaml
    restart: always
    networks:
      - app_kratos-net
