apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f configs.yml -o ../kubernetes
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: catalog-configs
  name: catalog-configs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalog-configs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f configs.yml -o ../kubernetes
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: catalog-configs
    spec:
      containers:
        - image: go-kratos/beer-catalog-configs:0.1.0
          name: catalog-configs
          resources: {}
      hostname: catalog-configs
      restartPolicy: Always
status: {}
